all: main.cpp AdminUI.cpp ControlerPizza.cpp Controlers.cpp Main_interface.cpp Models.cpp Pizza.cpp Pizza_UI.cpp Topping.cpp View.cpp
	g++ main.cpp AdminUI.cpp ControlerPizza.cpp Controlers.cpp Main_interface.cpp Models.cpp Pizza.cpp Pizza_UI.cpp Topping.cpp View.cpp

clean:
	rm a.out
